<?php
include_once("../includes/conn.php");
if (!empty($_POST['website'])) {
    echo "Spam bot detected.";
    exit;
}

$name    = trim($_POST['name'] ?? '');
$postId    = trim($_POST['post'] ?? '');
$message = trim($_POST['message'] ?? '');
$email   = trim($_POST['email'] ?? '');

$spamWords = [
    'viagra',
    'cialis',
    'levitra',
    'xanax',
    'valium',
    'phentermine',
    'casino',
    'poker',
    'blackjack',
    'gambling',
    'slots',
    'roulette',
    'bitcoin',
    'crypto',
    'blockchain',
    'investment',
    'forex',
    'stock',
    'http',
    'https',
    'www',
    '.com',
    '.net',
    '.org',
    'porn',
    'sex',
    'xxx',
    'adult',
    'escort',
    'nude',
    'fetish',
    'loan',
    'credit',
    'debt',
    'mortgage',
    'refinance',
    'win',
    'winner',
    'winning',
    'lottery',
    'prize',
    'free',
    'guaranteed',
    'money',
    'cash',
    'earn',
    'income',
    'rich',
    'profit',
    'work from home',
    'online income',
    'extra income',
    'weight loss',
    'diet',
    'fat loss',
    'lose weight',
    'miracle',
    'cure',
    'magic',
    'solution',
    'unsubscribe',
    'click here',
    'limited time',
    'urgent',
    'act now',
    'buy now',
    'order now',
    'shop now',
    'trial',
    'risk-free',
    'no cost',
    'hidden charges',
    'access now',
    'exclusive deal',
    'congratulations',
    'call now',
    'phone',
    'toll-free',
    '1-800',
    'contact us',
    'cheap',
    'lowest price',
    'bargain',
    'discount',
    'deal',
    'password',
    'account',
    'bank',
    'login',
    'verify',
    'Nigeria',
    'prince',
    'inheritance',
    'fund transfer',
    'million dollars',
    'wire transfer',
    'Western Union',
    'pharmacy',
    'meds',
    'pills',
    'drugs',
    'herbal',
    'dating',
    'singles',
    'match',
    'love',
    'romance',
    'get paid',
    'earn cash',
    'easy money',
    'fast cash',
    'investment opportunity',
    'no experience',
    'get rich quick',
    'click below',
    'see for yourself',
    'don’t delete',
    'this is not spam',
    'not junk',
    'real thing',
    'double your',
    'increase your',
    'explode your',
    'act immediately',
    'apply now',
    'be your own boss',
    'best price',
    'limited offer',
    'order today',
    'satisfaction guaranteed',
    'trial offer',
    'unsecured credit',
    'no credit check',
    'bad credit',
    'pre-approved',
    'insurance',
    'get insured',
    'affordable coverage',
    'bonus',
    'coupon',
    'voucher',
    'gift card',
    'free trial',
    'shocking',
    'truth about',
    'you won’t believe',
    'don’t miss out',
    'exclusive',
    'secret',
    'revolutionary',
    'urgent response needed',
    'risk free',
    'hidden charges',
    'luxury',
    'billionaire',
    'celeb',
    'fame',
    'malware',
    'spyware',
    'trojan',
    'virus',
    'hacked',
    'phishing',
    'scam',
    'fraud',
    'spoof',
    'spoofed',
    'unsubscribe here',
    'to be removed',
    'click to remove',
    'opt out',
    'this isn’t spam',
    'why am I getting this?',
    'money back',
    'limited time only',
    'no questions asked',
    'act now',
    'don’t wait',
    'while supplies last',
    'order now',
    'call today',
    'rush delivery',
    'get it now',
    'join free',
    'sign up free',
    'easy terms',
    'no obligation',
    'free gift',
    'this won’t last',
    'free info',
    'instant access',
    '100% free',
    'claim now',
    'get yours',
    'you’ve been selected',
    'exclusive offer',
    'limited availability',
    'available now',
    'pre-order',
    'reserve yours',
    'buy direct',
    'free consultation',
    'online biz opportunity',
    'earn extra',
    'make thousands',
    'daily income',
    'get started now',
    'financial freedom',
    'own boss',
    'mlm',
    'multi-level',
    'network marketing',
    'affiliate offer',
    'hot singles',
    'chat room',
    'naughty',
    'explicit',
    'cam girls',
    'live video',
    'streaming porn',
    'hardcore',
    'teen sex',
    'asian girls',
    'russian brides',
    'escort service',
    'unsecured debt',
    'fast loan',
    'instant approval',
    'cash advance',
    'payday loan',
    'quick funds',
    'consolidate debt',
    'lower your payment',
    'debt free',
    'cheap meds',
    'no prescription',
    'overseas pharmacy',
    'medication delivered',
    'prescription drugs',
    'nsa',
    'surveillance',
    'tracking',
    'spy camera',
    'illegal',
    'banned',
    'counterfeit',
    'knockoff',
    'replica',
    'fake',
    'unauthorized',
    'pirated',
    'torrent',
    'free download',
    'crack',
    'keygen',
    'serial'
];
foreach ($spamWords as $word) {
    if (stripos($message, $word) !== false) {
        echo "Some words might be spam or irrelevant. Please correct them and try again.";
        exit;
    }
}


// Basic validation
if ($name === '' || $message === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
    echo "Error: All fields are required and email must be valid.";
    exit;
}

// Optional: strip HTML tags early
$name    = strip_tags($name);
$message = strip_tags($message);

try {
    $stmt = $conn->prepare(
        "INSERT INTO comments (name, email, content,post_id)
         VALUES (:name, :email, :message, :post)"
    );
    $stmt->execute([
        ':name'    => $name,
        ':email'   => $email,
        ':message' => $message,
        ':post'    => $postId
    ]);
    $stmt = $conn->prepare("SELECT * FROM posts WHERE id = ?");
    $stmt->execute([$postId]);
    $post = $stmt->fetch(PDO::FETCH_ASSOC);

    $stmt = $conn->prepare(
        "INSERT INTO admin_notifications (notification_type, title, message,is_read)
         VALUES (:type, :title, :message, :is_read)"
    );
    $stmt->execute([
        ':type'    => "COMMENT",
        ':title'   => "New Comment",
        ':message' => "A new comment was posted on ".$post['title'],
        ':is_read'    => "0"
    ]);

    echo "success";
} catch (PDOException $e) {

    echo "Insert error: " . $e->getMessage();
}
